import fs from 'fs'
import YAML from 'yaml'

import input from './public/admin/config.mjs';

function insertComments(string) {
	const lines = string.split('\n');
	for (let index = 0; index < lines.length; index += 10) {
		lines.splice(index, 0, ['# Do not edit this file directly, edit config.mjs instead']);
	}
	return lines.join('\n')
}

fs.writeFileSync('./public/admin/config.yml', insertComments(YAML.stringify(input)));